# config/routes.yaml

# Route for displaying the list of users
user_index:
    path: /users
    controller: App\Controller\UserController::index

# Route for storing a new user (POST method)
users_store:
    path: /users/store
    controller: App\Controller\UserController::store

# Route for showing the edit form of a user (GET method)
users_edit:
    path: /users/{id}/edit
    controller: App\Controller\UserController::edit
    requirements:
        id: \d+

# Route for updating a user (POST method)
users_update:
    path: /users/{id}/update
    controller: App\Controller\UserController::update
    requirements:
        id: \d+

# Route for deleting a user (POST method)
users_delete:
    path: /users/{id}/delete
    controller: App\Controller\UserController::delete
    requirements:
        id: \d+
app_login:
    path: /login
    controller: App\Controller\AuthController::login

app_register:
    path: /register
    controller: App\Controller\AuthController::register

app_logout:
    path: /logout
